import type { Metadata } from "next";
import { Inter } from "next/font/google";  // Import the Inter font
import "./globals.css";

// Apply Inter font globally
const inter = Inter({
  variable: "--font-inter",  // Custom variable for the font
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Huonan App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}  // Apply the Inter font here
      >
        {children}
      </body>
    </html>
  );
}